# Brewfile of August Guidry brew tap (uncomment below to use) tap 'homebrew/boneyard' tap 'homebrew/bundle' tap 'homebrew/cask'
# tap 'homebrew/cask-drivers'
# tap 'homebrew/cask-fonts'
# tap 'homebrew/cask-versions'
# tap 'homebrew/core'
# tap 'homebrew/dev-tools'
# tap 'homebrew/services'

# "brew install [APP]"
brew 'aerc'
brew 'asdf'
brew 'bash'
brew 'buku'
brew 'calc'
brew 'clipboard'
brew 'cmus'
brew 'composer'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'docker-compose'
brew 'eza'
brew 'fastfetch'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'gnu-chess'
brew 'gpg'
brew 'groff'
brew 'himalaya'
brew 'htop'
brew 'hugo'
brew 'irssi'
brew 'ispell'
brew 'isync'
brew 'khal'
brew 'khard'
brew 'lazygit'
brew 'lighttpd'
brew 'livetex'
brew 'llm'
brew 'lynx'
brew 'mackup'
brew 'mas'
brew 'msmtp'
brew 'neomutt'
brew 'neovim'
brew 'newsboat'
brew 'notmuch'
brew 'pandoc'
brew 'pass'
brew 'pass-otp'
brew 'peco'
brew 'prettier'
brew 'proselint'
brew 'qemu'
brew 'ranger'
brew 'remind'
brew 'ripgrep'
brew 'ripmime'
brew 'sc-im'
brew 'shellcheck'
brew 'speedread'
brew 'speedtest-cli'
brew 'sqlite'
brew 'stow'
brew 'syncthing'
brew 'telnet'
brew 'thefuck'
brew 'tldr'
brew 'tmux'
brew 'tpm'
brew 'tree'
brew 'urlscan'
brew 'urlview'
brew 'vdirsyncer'
brew 'viu'
brew 'w3m'
brew 'webp'
brew 'wget'
brew 'whalebrew'
brew 'wifi-password'
brew 'xdg-ninja'
brew 'yadm'
brew 'yt-dlp'
brew 'z'
brew 'zoxide'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# "brew install --cask [APP]"
cask 'anki'
cask 'appcleaner'
cask 'blender'
cask 'calibre'
cask 'customshortcuts'
cask 'font-hack-nerd-font'
cask 'font-monaspace'
cask 'gemini'
cask 'gpg-suite'
cask 'iterm2'
cask 'keyclu'
cask 'krita'
cask 'librewolf', args: { no_quarantine: true }
cask 'love'
cask 'mactracker'
cask 'mpv'
cask 'musicbrainz-picard'
cask 'obs'
cask 'onedrive'
cask 'onyx'
cask 'openemu'
cask 'orion'
cask 'porting-kit'
cask 'sequel-ace'
cask 'soulseek'
cask 'the-unarchiver'
cask 'tor-browser'
cask 'transmission'
cask 'wacom-tablet'
cask 'wasabi-wallet'

# "mas install [APP]"
mas 'Xcode', id: 1419729466
mas 'Final Cut Pro', id: 424389933
mas 'Developer', id: 640199958
mas 'Keynote', id: 409183694
mas 'Userscripts-Mac-App', id: 1463298887
mas 'Dark Reader for Safari', id:1438243180
mas 'Pages', id: 409201541
mas 'Vimari', id: 1480933944
mas 'RSSHub Radar', id: 1610744717
mas 'Logic Pro', id: 634148309
mas 'Numbers', id: 409203825
mas 'FastVPN', id: 1419729466

# "whalebrew install [APP]"
# example: whalebrew 'whalebrew/wget'

# "vscode --install-extension [EXTENSION]"
# example: vscode "GitHub.codespaces"
